// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CorreiosAutomation.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Avaliação - Busca CEP e Rastreamento nos Correios")]
    public partial class Avaliacao_BuscaCEPERastreamentoNosCorreiosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Correios.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Features", "Avaliação - Busca CEP e Rastreamento nos Correios", "    Como QA responsável pela automação\r\n    Quero validar a busca de CEP e o rast" +
                    "reamento de encomendas no site dos Correios\r\n    Para garantir que os resultados" +
                    " exibidos estão corretos", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validar CEP inexistente, CEP existente e código de rastreio inválido")]
        [NUnit.Framework.CategoryAttribute("correios")]
        [NUnit.Framework.CategoryAttribute("busca-cep")]
        [NUnit.Framework.CategoryAttribute("rastreamento")]
        public async System.Threading.Tasks.Task ValidarCEPInexistenteCEPExistenteECodigoDeRastreioInvalido()
        {
            string[] tagsOfScenario = new string[] {
                    "correios",
                    "busca-cep",
                    "rastreamento"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar CEP inexistente, CEP existente e código de rastreio inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("que acesso a tela de busca de CEP dos Correios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.WhenAsync("pesquiso pelo CEP \"80700000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 11
    await testRunner.ThenAsync("o sistema deve confirmar que o CEP não existe", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 12
    await testRunner.WhenAsync("volto para a tela inicial de busca de CEP", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 13
    await testRunner.AndAsync("pesquiso pelo CEP \"01013-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 14
    await testRunner.ThenAsync("o resultado deve conter o endereço \"Rua Quinze de Novembro, São Paulo/SP\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 15
    await testRunner.WhenAsync("volto para a tela inicial de busca de CEP", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 16
    await testRunner.AndAsync("acesso o rastreamento pelo código \"SS987654321BR\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.ThenAsync("o sistema deve confirmar que o código de rastreio não está correto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 18
    await testRunner.AndAsync("fecho o navegador", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
